### ISSUE TITLE
My page

### ISSUE THREAD

**Issue by lse415** [ITTA-4-Team/Univey_Front#29]
## 📝Description
> Mypage

## ☑️Todo
- [ ] 마이페이지 메인
- [ ] 정보 수정
- [ ] 정보 수정 - 닉네임 중복 확인
- [ ] 설문 기록
- [ ] 설문 기록 - 마감 기능
- [ ] 포인트 내역 확인

## 💬 ETC
- 기타 사항
